version: '3.8'
services:
  phonebook:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./phonebook.xml:/app/phonebook.xml
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

